### ISSUE TITLE
[Bug] When running npm start

### ISSUE THREAD

**Issue by TechDude98** [Dev-CasperTheGhost/snaily-cadv3#20]
**Describe the bug**
When installing and following the final step, 'npm start' in the snaily-cadv3 folder, it shows the following message:

ubuntu@ip-172-31-44-243:~/snaily-cadv3$ npm start

> snaily-cadv3@0.1.0 start /home/ubuntu/snaily-cadv3
> concurrently "npm run start:server" "npm run start:client"

sh: 1: concurrently: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! snaily-cadv3@0.1.0 start: `concurrently "npm run start:server" "npm run start:client"`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the snaily-cadv3@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T17_46_31_519Z-debug.log

**Screenshots**

**Comment by Dev-CasperTheGhost** [comment]
Ah, that's my bad, forgot to mention, in the main folder (snaily-cadv3) run `npm install` as well.

**Comment by TechDude98** [comment]
Did that, now I'm getting this:

`buntu@ip-172-31-44-243:~/snaily-cadv3$ sudo npm start

> snaily-cadv3@0.1.0 start /home/ubuntu/snaily-cadv3
> concurrently "npm run start:server" "npm run start:client"

[0]
[0] > snaily-cadv3@0.1.0 start:server /home/ubuntu/snaily-cadv3
[0] > npm start --prefix server
[0]
[1]
[1] > snaily-cadv3@0.1.0 start:client /home/ubuntu/snaily-cadv3
[1] > npm run serve --prefix client
[1]
[0]
[0] > server@1.0.0 start /home/ubuntu/snaily-cadv3/server
[0] > nodemon src/server.ts
[0]
[1]
[1] > client@1.0.0 serve /home/ubuntu/snaily-cadv3/client
[1] > serve -s build -l 5000
[1]
[1] sh: 1: serve: not found
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! syscall spawn
[1] npm ERR! file sh
[1] npm ERR! errno ENOENT
[1] npm ERR! client@1.0.0 serve: `serve -s build -l 5000`
[1] npm ERR! spawn ENOENT
[1] npm ERR!
[1] npm ERR! Failed at the client@1.0.0 serve script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T18_49_48_050Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! snaily-cadv3@0.1.0 start:client: `npm run serve --prefix client`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the snaily-cadv3@0.1.0 start:client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T18_49_48_087Z-debug.log
[1] npm run start:client exited with code 1
[0] [nodemon] 2.0.6
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: ts,json
[0] [nodemon] starting `ts-node src/server.ts`
[0] /home/ubuntu/snaily-cadv3/server/config:12
[0] export default config;
[0] ^^^^^^
[0]
[0] SyntaxError: Unexpected token export
[0]     at Module._compile (internal/modules/cjs/loader.js:723:23)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
[0]     at Module.load (internal/modules/cjs/loader.js:653:32)
[0]     at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:585:3)
[0]     at Module.require (internal/modules/cjs/loader.js:692:17)
[0]     at require (internal/modules/cjs/helpers.js:25:18)
[0]     at Object.<anonymous> (/home/ubuntu/snaily-cadv3/server/src/lib/checks.ts:3:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:778:30)
[0]     at Module.m._compile (/home/ubuntu/snaily-cadv3/server/node_modules/ts-node/src/index.ts:1043:23)
[0] [nodemon] app crashed - waiting for file changes before starting...
`

**Comment by Dev-CasperTheGhost** [comment]
do you have the latest version of nodejs installed?

**Comment by Dev-CasperTheGhost** [comment]
And try installing typescript globally using `npm install typescript -g`

**Comment by TechDude98** [comment]
v10.23.0 is installed

**Comment by Dev-CasperTheGhost** [comment]
yeah, that might be the problem, can you upgrade to +v12

**Comment by TechDude98** [comment]
Let me try that, I'll update you in a few.

**Comment by TechDude98** [comment]
Now on v.14.15.0, still with the same error.


> concurrently "npm run start:server" "npm run start:client"

[1]
[1] > snaily-cadv3@0.1.0 start:client /home/ubuntu/snaily-cadv3
[1] > npm run serve --prefix client
[1]
[0]
[0] > snaily-cadv3@0.1.0 start:server /home/ubuntu/snaily-cadv3
[0] > npm start --prefix server
[0]
[1]
[1] > client@1.0.0 serve /home/ubuntu/snaily-cadv3/client
[1] > serve -s build -l 5000
[1]
[0]
[0] > server@1.0.0 start /home/ubuntu/snaily-cadv3/server
[0] > nodemon src/server.ts
[0]
[1] sh: 1: serve: not found
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! syscall spawn
[1] npm ERR! file sh
[1] npm ERR! errno ENOENT
[1] npm ERR! client@1.0.0 serve: `serve -s build -l 5000`
[1] npm ERR! spawn ENOENT
[1] npm ERR!
[1] npm ERR! Failed at the client@1.0.0 serve script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T18_59_27_272Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! snaily-cadv3@0.1.0 start:client: `npm run serve --prefix client`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the snaily-cadv3@0.1.0 start:client script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T18_59_27_308Z-debug.log
[1] npm run start:client exited with code 1
[0] [nodemon] 2.0.6
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: ts,json
[0] [nodemon] starting `ts-node src/server.ts`
[0] /home/ubuntu/snaily-cadv3/server/config:12
[0] export default config;
[0] ^^^^^^
[0]
[0] SyntaxError: Unexpected token 'export'
[0]     at wrapSafe (internal/modules/cjs/loader.js:979:16)
[0]     at Module._compile (internal/modules/cjs/loader.js:1027:27)
[0]     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
[0]     at Module.load (internal/modules/cjs/loader.js:928:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
[0]     at Module.require (internal/modules/cjs/loader.js:952:19)
[0]     at require (internal/modules/cjs/helpers.js:88:18)
[0]     at Object.<anonymous> (/home/ubuntu/snaily-cadv3/server/src/lib/checks.ts:3:1)
[0]     at Module._compile (internal/modules/cjs/loader.js:1063:30)
[0]     at Module.m._compile (/home/ubuntu/snaily-cadv3/server/node_modules/ts-node/src/index.ts:1043:23)
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by TechDude98** [comment]
It appears to be an issue with the '/home/ubuntu/snaily-cadv3/server/config' file, line 12 from the output (from my little knowledge of Ubuntu server admin/programming experience)

**Comment by Dev-CasperTheGhost** [comment]
For the first error, in the `client` folder run `npm install serve -g` and for the second error try `npm run build` in the `server` folder, then to start it, edit `package.json` in the `server` folder in the start script, change from `nodemon src/server.ts` to  `node src/server.js`

**Comment by TechDude98** [comment]
Well, I got through that! I just had to delete the config and rename it to the correct extension... Silly me. 

So a question, I know previously to get v2 to work on an external IP via a VPS, you had to edit a few of the config files. I'm assuming that's still the case, correct?

**Comment by Dev-CasperTheGhost** [comment]
Cool! Yes that's still the case

**Comment by Dev-CasperTheGhost** [comment]
First config: `client/config.ts`
Second config: `server/config.ts`

**Comment by TechDude98** [comment]
In my `client` folder, there is no `config.ts` file.. The only one that's similar is `tsconfig.json`

**Comment by Dev-CasperTheGhost** [comment]
Sorry, it's in `client/src/config.ts`

**Comment by TechDude98** [comment]
Do I have to edit anything in `server/config.js`?

**Comment by Dev-CasperTheGhost** [comment]
Yes, the URL to the client and your database credentials.

**Comment by TechDude98** [comment]
Alright, figured as much. Just changed all of that, installed and followed your steps above

> For the first error, in the client folder run npm install serve -g and for the second error try npm run build in the server folder, then to start it, edit package.json in the server folder in the start script, change from nodemon src/server.ts to node src/server.js

This gave me the following error when I ran npm start:
> snaily-cadv3@0.1.0 start
> concurrently "npm run start:server" "npm run start:client"

[1]
[1] > snaily-cadv3@0.1.0 start:client
[1] > npm run serve --prefix client
[1]
[0]
[0] > snaily-cadv3@0.1.0 start:server
[0] > npm start --prefix server
[0]
[1]
[1] > client@1.0.0 serve
[1] > serve -s build -l 5000
[1]
[0]
[0] > server@1.0.0 start
[0] > node src/server.ts
[0]
[1] sh: 1: serve: not found
[1] npm ERR! code 127
[1] npm ERR! path /home/ubuntu/snaily-cadv3/client
[1] npm ERR! command failed
[1] npm ERR! command sh -c serve -s build -l 5000
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_10_00_367Z-debug.log
[1] npm ERR! code 127
[1] npm ERR! path /home/ubuntu/snaily-cadv3
[1] npm ERR! command failed
[1] npm ERR! command sh -c npm run serve --prefix client
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_10_00_382Z-debug.log
[1] npm run start:client exited with code 127
[0] (node:10690) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
[0] (Use `node --trace-warnings ...` to show where the warning was created)
[0] /home/ubuntu/snaily-cadv3/server/src/server.ts:1
[0] import "./lib/checks";
[0] ^^^^^^
[0]
[0] SyntaxError: Cannot use import statement outside a module
[0]     at wrapSafe (node:internal/modules/cjs/loader:999:16)
[0]     at Module._compile (node:internal/modules/cjs/loader:1047:27)
[0]     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1112:10)
[0]     at Module.load (node:internal/modules/cjs/loader:948:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:789:14)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:72:12)
[0]     at node:internal/main/run_main_module:17:47
[0] npm ERR! code 1
[0] npm ERR! path /home/ubuntu/snaily-cadv3/server
[0] npm ERR! command failed
[0] npm ERR! command sh -c node src/server.ts
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_10_00_433Z-debug.log
[0] npm ERR! code 1
[0] npm ERR! path /home/ubuntu/snaily-cadv3
[0] npm ERR! command failed
[0] npm ERR! command sh -c npm start --prefix server
[0]
[0] npm ERR! A complete log of this run can be found in:
[0] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_10_00_451Z-debug.log
[0] npm run start:server exited with code 1
npm ERR! code 1
npm ERR! path /home/ubuntu/snaily-cadv3
npm ERR! command failed
npm ERR! command sh -c concurrently "npm run start:server" "npm run start:client"

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_10_00_474Z-debug.log

**Comment by TechDude98** [comment]
It says:
[1] INFO: Accepting connections at http://localhost:5000
[0] [MAIN][19:15:55]: SERVER RUNNING ON 3030
[0] [UPDATER][19:15:55]: Your CAD version is up to date.

I opened port 3030 TCP, 80 TCP for inbound connections, and it says it's refusing to connect when I type in the public IP. Changed around the config files to point to the public IP address of the server as before.

**Comment by Dev-CasperTheGhost** [comment]
Yeah, in `client/package.json` the port is still set to 5000; you can change that and restart the CAD.

**Comment by Dev-CasperTheGhost** [comment]
At: `scripts` > `serve` > `serve -d - l 5000` change the 5000 to any port you'd like.

**Comment by TechDude98** [comment]
Changed `client/package.json` file under to port 80, now it is giving me this error again..

But my `package.json` file had the following for scripts > serve:
`"serve": "serve -s build -l 80",`


[1] sh: 1: serve: not found
[1] npm ERR! code 127
[1] npm ERR! path /home/ubuntu/snaily-cadv3/client
[1] npm ERR! command failed
[1] npm ERR! command sh -c serve -s build -l 80
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_22_46_363Z-debug.log
[1] npm ERR! code 127
[1] npm ERR! path /home/ubuntu/snaily-cadv3
[1] npm ERR! command failed
[1] npm ERR! command sh -c npm run serve --prefix client
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_22_46_384Z-debug.log

**Comment by Dev-CasperTheGhost** [comment]
Did you run `npm install -g serve`? Ifso, try `sudo npm install -g serve`

**Comment by TechDude98** [comment]
Well, that did alright. Now it just says this:

> [1] ERROR: Failed to serve: Error: listen EACCES: permission denied 0.0.0.0:80
[1]     at Server.setupListenHandle [as _listen2] (node:net:1269:21)
[1]     at listenInCluster (node:net:1334:12)
[1]     at Server.listen (node:net:1420:7)
[1]     at startEndpoint (/usr/local/lib/node_modules/serve/bin/serve.js:216:19)
[1]     at /usr/local/lib/node_modules/serve/bin/serve.js:440:3
[1]
[1] INFO: Gracefully shutting down. Please wait...
[1] npm ERR! code 1
[1] npm ERR! path /home/ubuntu/snaily-cadv3/client
[1] npm ERR! command failed
[1] npm ERR! command sh -c serve -s build -l 80
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_26_56_523Z-debug.log
[1] npm ERR! code 1
[1] npm ERR! path /home/ubuntu/snaily-cadv3
[1] npm ERR! command failed
[1] npm ERR! command sh -c npm run serve --prefix client
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     /home/ubuntu/.npm/_logs/2020-11-02T19_26_56_549Z-debug.log
[1] npm run start:client exited with code 1
[0] [MAIN][19:26:57]: SERVER RUNNING ON 3030
[0] [UPDATER][19:26:57]: Your CAD version is up to date.

**Comment by Dev-CasperTheGhost** [comment]
Is there anything else running on port 80?

Try adding `sudo` to the serve script in `client/package.json`

**Comment by TechDude98** [comment]
That did it. Nothing else is running on port 80. Now when you navigate to the IP, it just says "404 | The requested path could not be found"

**Comment by Dev-CasperTheGhost** [comment]
Run `npm run build` in the client folder, that's my bad again..

**Comment by TechDude98** [comment]
No worries, welcome to programming! There will always be bugs, especially on the first brand new release.

**Comment by Dev-CasperTheGhost** [comment]
Yeah haha

**Comment by TechDude98** [comment]
Do you have any suggestions for auto-starting when the server restarts? I tried using pm2 but it wasn't working correctly on v2.

**Comment by Dev-CasperTheGhost** [comment]
My only suggestion would be pm2, you can try again on v3, my guesses:

client: pm2 start npm --name cad-client -- run serve
server: pm2 start npm --name cad-server -- run start
