### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by GrimaceXX** [Dev-CasperTheGhost/snaily-cadv3#51]
**Describe the bug**Error Given after following all steps

C:\Users\matt9\snaily-cadv3\client>npm start

> client@1.0.0 start
> react-scripts start

C:\Users\matt9\snaily-cadv3\client\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:239
      appTsConfig.compilerOptions[option] = value;
                                          ^

TypeError: Cannot assign to read only property 'jsx' of object '#<Object>'
    at verifyTypeScriptSetup (C:\Users\matt9\snaily-cadv3\client\node_modules\react-scripts\scripts\utils\verifyTypeScriptSetup.js:239:43)
    at Object.<anonymous> (C:\Users\matt9\snaily-cadv3\client\node_modules\react-scripts\scripts\start.js:31:1)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
npm ERR! code 1
npm ERR! path C:\Users\matt9\snaily-cadv3\client
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c react-scripts start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\matt9\AppData\Local\npm-cache\_logs\2020-12-09T23_47_07_358Z-debug.log

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by Dev-CasperTheGhost** [comment]
Try updating typescript or installing it globally

**Comment by GrimaceXX** [comment]
So I updated typescript then got this error:
I also added you on Discord 
[1]
[1] > client@1.0.0 serve
[1] > serve -s build -l 5000
[1]
[1] 'serve' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] npm ERR! code 1
[1] npm ERR! path C:\Users\matt9\snaily-cadv3\client
[1] npm ERR! command failed
[1] npm ERR! command C:\Windows\system32\cmd.exe /d /s /c serve -s build -l 5000
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\matt9\AppData\Local\npm-cache\_logs\2020-12-10T15_13_27_099Z-debug.log
[1] npm ERR! code 1
[1] npm ERR! path C:\Users\matt9\snaily-cadv3
[1] npm ERR! command failed
[1] npm ERR! command C:\Windows\system32\cmd.exe /d /s /c npm run serve --prefix client
[1]
npm ERR! A complete log of this run can be found in:
[1] npm ERR!     C:\Users\matt9\AppData\Local\npm-cache\_logs\2020-12-10T15_13_27_192Z-debug.log
[1] npm run start:client exited with code 1
[0] [nodemon] 2.0.6
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: ts,json
[0] [nodemon] starting `ts-node src/server.ts`
[0] 'ts-node' is not recognized as an internal or external command,
[0] operable program or batch file.
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by Dev-CasperTheGhost** [comment]
Run: `npm install -g ts-node serve`, that should fix your issue I think

**Comment by GrimaceXX** [comment]
Looks like its trying to work now, I get the page to pull up but everything stuck with a loading circle

this error pops now

[1] INFO: Accepting connections at http://localhost:5000
[0]
[0] C:\Users\matt9\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:513
[0]     return new TSError(diagnosticText, diagnosticCodes)
[0]            ^
[0] TSError: ⨯ Unable to compile TypeScript:
[0] src/server.ts(3,20): error TS2307: Cannot find module '../config' or its corresponding type declarations.
[0] src/server.ts(16,12): error TS2349: This expression is not callable.
[0]   Type 'typeof import("C:/Users/matt9/snaily-cadv3/server/node_modules/socket.io/dist/index")' has no call signatures.
[0]
[0]     at createTSError (C:\Users\matt9\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:513:12)
[0]     at reportTSError (C:\Users\matt9\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:517:19)
[0]     at getOutput (C:\Users\matt9\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:752:36)
[0]     at Object.compile (C:\Users\matt9\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:968:32)
[0]     at Module.m._compile (C:\Users\matt9\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1056:42)
[0]     at Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
[0]     at Object.require.extensions.<computed> [as .ts] (C:\Users\matt9\AppData\Roaming\npm\node_modules\ts-node\src\index.ts:1059:12)
[0]     at Module.load (node:internal/modules/cjs/loader:973:32)
[0]     at Function.Module._load (node:internal/modules/cjs/loader:813:14)
[0]     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
[0] [nodemon] app crashed - waiting for file changes before starting...

**Comment by Dev-CasperTheGhost** [comment]
Make sure to update your local clone to the latest version. The second issue is that the config file was not found in the server folder, make sure to rename `config.example.ts` to `config.ts` in `server` folder.

**Comment by Dev-CasperTheGhost** [comment]
Closing due to inactivity.
